### ISSUE TITLE
Get a release out the door!

### ISSUE THREAD

**Issue by mlaccetti** [spring-social-google/spring-social-google#102]
- [x] Fix the crazy gradle build
- [x] Introduce `Checkstyle` to achieve a unified code style
- [x] Introduce `EditorConfig` to do the same as `Checkstyle`, but in the IDE
- [x] Introduce `FindBugs` to chase down bad things

**Comment by NoelWuyts** [comment]
Any progress?

**Comment by mlaccetti** [comment]
@NoelWuyts On vacation, so taking a stab at it, finally.

**Comment by mlaccetti** [comment]
1.1.0 has been released!

**Comment by NoelWuyts** [comment]
top!

**Comment by NoelWuyts** [comment]
Will there also be a release on maven central?

**Comment by mlaccetti** [comment]
@NoelWuyts Working with bintray.com to sync things to Maven Central. For now, you can snag `1.1.1` from bintray via Gradle/Maven (https://bintray.com/spring-social-google/jars/spring-social-google/1.1.1) and hopefully shortly from Central.

**Comment by NoelWuyts** [comment]
ok thx

**Comment by hinotori** [comment]
hello people, i'm just a curious developer
is it ready for Spring Security 5? Ney changes in oauth authentication

https://spring.io/blog/2017/05/11/spring-security-5-0-0-m1#new-support-for-oauth-2-0-and-openid-connect-1-0

regards

2017-05-22 16:33 GMT-03:00 Noël Wuyts <notifications@github.com>:

**Comment by mlaccetti** [comment]
@hinotori open a new issue, can track it there.

**Comment by mlaccetti** [comment]
Just a quick note - we had to change from `org.springframework.social:spring-social-google` to `com.github.spring-social:spring-social-google` - this is due to getting things synced to Maven Central and not being part of Spring itself.

**Comment by GabiAxel** [comment]
I remember I had permission to publish to SpringSource Maven repository which got synced to Central, so I could use the org.springframework.social groupId and I wasn't a SpringSource employee. Can't you get permission from anyone at SpringSource to do the same? Maybe @habuma can help?

**Comment by mlaccetti** [comment]
I had a ticket open on [Sonatype's JIRA](https://issues.sonatype.org/browse/OSSRH-31461), and the Spring rep suggested that they changed their guidelines, etc. Given that this and one other Spring Social community project seem to be actively maintained, I'm not sure the best approach for this. I'm open to suggestions!
