### ISSUE TITLE
Tag and release from Maven Central

### ISSUE THREAD

**Issue by raulgd** [spring-social-google/spring-social-google#87]
Hi,

I see that on Maven Central there is a 1.0.0.RELEASE version, and checking this repo tags that seems to be the latest, but checking master I see a lot of changes since 1.0.0.RELEASE but still there hasn't been any releases (tags) since then, also I'm checking the gradle build scripts and also there's no version definition in there.

So what is recommended? I would use this on Spring Boot, so is 1.0.0.RELEASE enough? does it contain the auto-configuration and such?

And if there are a lot of changes since then, why there hasn't been any releases to Maven Central? is it a Spring project policy stopping it?

Thanks

**Comment by mlaccetti** [comment]
Just a matter of time - trying to nail down a bunch of stuff, make sure it is all tested, then cut a release.  No ETA at this time.

**Comment by raulgd** [comment]
Anything I could help with?

**Comment by mlaccetti** [comment]
If you can figure out how to make clones, I'd be all over that.

1.0.0 is certainly enough to get folks signing in.

**Comment by leon** [comment]
I'd really like to see the autoconfiguration bits getting published to maven.
Anything I can do to help?

**Comment by NoelWuyts** [comment]
I would really like to see a new release! 

Is there anything we can help with?

**Comment by mlaccetti** [comment]
Totally spaced - let me chase this down and get a release out.

**Comment by NoelWuyts** [comment]
When can we expect any progress in the new release?

**Comment by mlaccetti** [comment]
1.1.0 is out.

**Comment by shettysamarth** [comment]
1.1.0 is not deployed to maven central.
Can we have it as 1.1.0.RELEASE.
